// Mock data for models
export interface Model {
  id: string;
  name: string;
  provider: string;
  providerLogo: string;
  description: string;
  contextLength: number;
  inputPrice: number; // per 1M tokens
  outputPrice: number; // per 1M tokens
  tags: string[];
  isNew?: boolean;
  isFree?: boolean;
  throughput?: string;
  latency?: string;
}

export const models: Model[] = [
  {
    id: "anthropic/claude-3.5-sonnet",
    name: "Claude 3.5 Sonnet",
    provider: "Anthropic",
    providerLogo: "A",
    description: "Claude 3.5 Sonnet delivers better-than-Opus capabilities at a faster speed.",
    contextLength: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    tags: ["chat", "code", "reasoning"],
    isNew: true,
  },
  {
    id: "openai/gpt-4o",
    name: "GPT-4o",
    provider: "OpenAI",
    providerLogo: "O",
    description: "GPT-4o is OpenAI's most advanced multimodal model.",
    contextLength: 128000,
    inputPrice: 2.5,
    outputPrice: 10.0,
    tags: ["chat", "vision", "code"],
  },
  {
    id: "google/gemini-2.0-flash",
    name: "Gemini 2.0 Flash",
    provider: "Google",
    providerLogo: "G",
    description: "Fast and efficient model for everyday tasks.",
    contextLength: 1000000,
    inputPrice: 0.075,
    outputPrice: 0.30,
    tags: ["chat", "fast"],
    isNew: true,
  },
  {
    id: "meta/llama-3.3-70b",
    name: "Llama 3.3 70B",
    provider: "Meta",
    providerLogo: "M",
    description: "Meta's latest open-source large language model.",
    contextLength: 131072,
    inputPrice: 0.12,
    outputPrice: 0.30,
    tags: ["chat", "open-source"],
  },
  {
    id: "anthropic/claude-3-opus",
    name: "Claude 3 Opus",
    provider: "Anthropic",
    providerLogo: "A",
    description: "Most powerful Claude model for complex tasks.",
    contextLength: 200000,
    inputPrice: 15.0,
    outputPrice: 75.0,
    tags: ["chat", "reasoning", "code"],
  },
  {
    id: "mistralai/mistral-large",
    name: "Mistral Large",
    provider: "Mistral AI",
    providerLogo: "M",
    description: "Mistral's flagship model with top-tier reasoning.",
    contextLength: 128000,
    inputPrice: 2.0,
    outputPrice: 6.0,
    tags: ["chat", "reasoning"],
  },
  {
    id: "deepseek/deepseek-v3",
    name: "DeepSeek V3",
    provider: "DeepSeek",
    providerLogo: "D",
    description: "Advanced model with strong coding capabilities.",
    contextLength: 64000,
    inputPrice: 0.14,
    outputPrice: 0.28,
    tags: ["chat", "code"],
    isNew: true,
  },
  {
    id: "qwen/qwen-2.5-72b",
    name: "Qwen 2.5 72B",
    provider: "Alibaba",
    providerLogo: "Q",
    description: "Alibaba's latest multilingual large model.",
    contextLength: 131072,
    inputPrice: 0.35,
    outputPrice: 0.40,
    tags: ["chat", "multilingual"],
  },
  {
    id: "google/gemini-1.5-pro",
    name: "Gemini 1.5 Pro",
    provider: "Google",
    providerLogo: "G",
    description: "Google's multimodal model with 1M context window.",
    contextLength: 2000000,
    inputPrice: 1.25,
    outputPrice: 5.0,
    tags: ["chat", "vision", "long-context"],
  },
  {
    id: "cohere/command-r-plus",
    name: "Command R+",
    provider: "Cohere",
    providerLogo: "C",
    description: "Enterprise-grade model optimized for RAG.",
    contextLength: 128000,
    inputPrice: 2.5,
    outputPrice: 10.0,
    tags: ["chat", "rag"],
  },
  {
    id: "openai/gpt-4-turbo",
    name: "GPT-4 Turbo",
    provider: "OpenAI",
    providerLogo: "O",
    description: "Faster and cheaper version of GPT-4.",
    contextLength: 128000,
    inputPrice: 10.0,
    outputPrice: 30.0,
    tags: ["chat", "vision", "code"],
  },
  {
    id: "anthropic/claude-3-haiku",
    name: "Claude 3 Haiku",
    provider: "Anthropic",
    providerLogo: "A",
    description: "Fast and affordable Claude model.",
    contextLength: 200000,
    inputPrice: 0.25,
    outputPrice: 1.25,
    tags: ["chat", "fast"],
  },
  {
    id: "huggingface/zephyr-7b",
    name: "Zephyr 7B",
    provider: "Hugging Face",
    providerLogo: "H",
    description: "Fine-tuned Mistral 7B for helpfulness.",
    contextLength: 32768,
    inputPrice: 0,
    outputPrice: 0,
    tags: ["chat", "free"],
    isFree: true,
  },
  {
    id: "nousresearch/hermes-3-405b",
    name: "Hermes 3 405B",
    provider: "Nous Research",
    providerLogo: "N",
    description: "Largest open-source model with advanced capabilities.",
    contextLength: 131072,
    inputPrice: 0.80,
    outputPrice: 0.80,
    tags: ["chat", "open-source"],
  },
  {
    id: "perplexity/sonar-large",
    name: "Sonar Large",
    provider: "Perplexity",
    providerLogo: "P",
    description: "Online model with real-time web search.",
    contextLength: 127072,
    inputPrice: 1.0,
    outputPrice: 1.0,
    tags: ["chat", "search"],
  },
];

export const categories = [
  { id: "all", name: "All Models", count: models.length },
  { id: "chat", name: "Chat", count: models.filter(m => m.tags.includes("chat")).length },
  { id: "code", name: "Code", count: models.filter(m => m.tags.includes("code")).length },
  { id: "vision", name: "Vision", count: models.filter(m => m.tags.includes("vision")).length },
  { id: "reasoning", name: "Reasoning", count: models.filter(m => m.tags.includes("reasoning")).length },
  { id: "free", name: "Free", count: models.filter(m => m.isFree).length },
];

export const providers = [
  "Anthropic",
  "OpenAI",
  "Google",
  "Meta",
  "Mistral AI",
  "DeepSeek",
  "Alibaba",
  "Cohere",
  "Hugging Face",
  "Nous Research",
  "Perplexity",
];
